Special NumPy Arrays
- Array filled with 0's
- Arrys filled with 1's
- Create an empty array
- An array with a range of elements
- Array disgonal element filled with 1's
- Create an array with values that are spaced linearly in a specified interval

# zeros

In [1]:
import numpy as np
ar_zero = np.zeros(4)
print(ar_zero)

[0. 0. 0. 0.]


In [2]:
ar_zero1 = np.zeros((3,4))
print(ar_zero1)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# ones

In [5]:
ar_one = np.ones((2,4))
print(ar_one)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


# empty

In [10]:
ar_em = np.empty(4)
print(ar_em)

[1. 1. 1. 1.]


In [13]:
ar_em = np.empty((2,4))
print(ar_em)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


# range of elements

In [7]:
ar_rn = np.arange(4)
print(ar_rn)

[0 1 2 3]


# diagonal

In [8]:
ar_dia = np.eye(3)
print(ar_dia)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [9]:
ar_dia = np.eye(3,5)
print(ar_dia)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


# linspace

In [11]:
ar_lin = np.linspace(1, 10, num=5)
print(ar_lin)

[ 1.    3.25  5.5   7.75 10.  ]


In [12]:
ar_lin = np.linspace(0, 10, num=4)
print(ar_lin)

[ 0.          3.33333333  6.66666667 10.        ]


Certainly! Let's go through creating special NumPy arrays for each of the scenarios you mentioned:

### 1. Array filled with 0's:
```python
import numpy as np

zeros_array = np.zeros((3, 4))  # Create a 3x4 array filled with zeros
print(zeros_array)
```

### 2. Array filled with 1's:
```python
ones_array = np.ones((2, 3))  # Create a 2x3 array filled with ones
print(ones_array)
```

### 3. Create an empty array:
An empty array is created, but the values are not initialized. The content of the array will be whatever is already in that memory location.

```python
empty_array = np.empty((2, 2))  # Create a 2x2 empty array
print(empty_array)
```

### 4. An array with a range of elements:
You can use `np.arange()` to create an array with a range of values.

```python
range_array = np.arange(0, 10, 2)  # Create an array with values from 0 to 10 (exclusive) with a step of 2
print(range_array)
```

### 5. Array diagonal elements filled with 1's:
```python
identity_matrix = np.eye(3)  # Create a 3x3 identity matrix with diagonal elements as 1's
print(identity_matrix)
```

### 6. Create an array with values spaced linearly in a specified interval:
You can use `np.linspace()` to create an array with evenly spaced values over a specified interval.

```python
linear_space_array = np.linspace(0, 1, 5)  # Create an array with 5 values spaced evenly between 0 and 1
print(linear_space_array)
```

These are examples of how to create special NumPy arrays for different use cases. Adjust the parameters of the functions based on your specific requirements.