Shape & Reshaping in NumPy Arrays:

In [6]:
import numpy as np

# Shape

var = np.array([[1,2,3,4],[11,22,33,44]])
print(var)

[[ 1  2  3  4]
 [11 22 33 44]]


In [7]:
print(var.shape)

(2, 4)


In [8]:
var1 = np.array([1,2,3,4], ndmin=4)

In [9]:
print(var1)

[[[[1 2 3 4]]]]


In [10]:
print(var1.ndim)

4


In [11]:
print(var1.shape)

(1, 1, 1, 4)


In [21]:
# Reshape

var2 = np.array([1,2,3,4,5,6])
print(var2)
print(var2.ndim)


x = var2.reshape(3,2)
print(x)
print(x.ndim)

[1 2 3 4 5 6]
1
[[1 2]
 [3 4]
 [5 6]]
2


In [19]:
x = var2.reshape(2,3)
print(x)

[[1 2 3]
 [4 5 6]]


In [22]:
# Reshape

var2 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(var2)
print(var2.ndim)


x = var2.reshape(2,3,2)
print(x)
print(x.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3


In [25]:
x = x.reshape(-1) # to convert into one-dimensional
print(x)
print(x.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1
