Creating NumPy Arrays
- use function np.array()
- ndarray (n-dimensional array)

In [1]:
import numpy as np
a = np.array([1,2,3])
print(a)

[1 2 3]


In [2]:
x = [1,2,3,4] # python list
y = np.array(x) # converted to numpy array
print(y)

[1 2 3 4]


In [4]:
print(type(x))
print(type(y))

<class 'list'>
<class 'numpy.ndarray'>


In [5]:
l = []

for i in range(1,5):
    int_1 = input("enter:")
    l.append(int_1)

print(np.array(l))

['14' '15' '98' '78']


Dimensions in Arrays:
- 1-D Arrays [1 2 3 4]
- 2-D Arrays [[ ]]
- 3-D Arrays [[[ ]]]
- Higher Dimensional Arrays


- use ndim function to check dimensions

In [6]:
print(y.ndim)

1


In [7]:
ar2 = np.array([[1,2,3,4], [1,2,3,4]])
print(ar2)
print(ar2.ndim)

[[1 2 3 4]
 [1 2 3 4]]
2


In [8]:
ar3 = np.array([[[1,2,3,4],[1,2,3,4],[1,2,3,4]]])
print(ar3)
print(ar3.ndim)

[[[1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]]]
3


In [10]:
arn = np.array([1,2,3,4], ndmin=10) # creating 10 dimensional array
print(arn)
print(arn.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10


NumPy is a fundamental package for scientific computing in Python, particularly for working with large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays. Here's a brief guide on creating NumPy arrays:

### 1. **Importing NumPy:**
   To use NumPy, you need to import it into your Python script or Jupyter notebook:

   ```python
   import numpy as np
   ```

### 2. **Creating Arrays:**

#### a. **From Python Lists:**
   You can create a NumPy array from a Python list using the `np.array()` function:

   ```python
   my_list = [1, 2, 3, 4, 5]
   my_array = np.array(my_list)
   ```

#### b. **Specifying Data Type:**
   You can explicitly specify the data type of the array elements using the `dtype` parameter:

   ```python
   my_array = np.array([1, 2, 3, 4, 5], dtype=np.float64)
   ```

#### c. **Multi-dimensional Arrays:**
   NumPy arrays can be multi-dimensional. You can create 2D arrays using nested lists:

   ```python
   nested_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
   my_2d_array = np.array(nested_list)
   ```

   For higher-dimensional arrays, you can nest lists further.

### 3. **Special Arrays:**

#### a. **Zeros and Ones:**
   You can create arrays of zeros or ones using `np.zeros()` and `np.ones()`:

   ```python
   zeros_array = np.zeros((3, 4))  # 3x4 array of zeros
   ones_array = np.ones((2, 3))    # 2x3 array of ones
   ```

#### b. **Identity Matrix:**
   To create an identity matrix, you can use `np.eye()`:

   ```python
   identity_matrix = np.eye(3)  # 3x3 identity matrix
   ```

### 4. **Array Operations:**

#### a. **Array Arithmetic:**
   NumPy arrays support element-wise arithmetic operations:

   ```python
   a = np.array([1, 2, 3])
   b = np.array([4, 5, 6])

   sum_array = a + b
   difference_array = a - b
   product_array = a * b
   ```

#### b. **Universal Functions (ufuncs):**
   NumPy provides a range of universal functions for element-wise operations, such as `np.sin()`, `np.cos()`, `np.exp()`, etc.

   ```python
   angle_array = np.array([0, np.pi/2, np.pi])
   sin_values = np.sin(angle_array)
   ```

### 5. **Array Slicing and Indexing:**
   You can access elements, rows, and columns of NumPy arrays using indexing and slicing:

   ```python
   my_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

   # Accessing elements
   element = my_array[0, 1]  # 2nd element in the 1st row

   # Slicing
   row_slice = my_array[1, :]   # 2nd row
   column_slice = my_array[:, 2]  # 3rd column
   ```

### 6. **Array Shape and Reshaping:**
   You can check and change the shape of an array using `shape` and `reshape`:

   ```python
   original_array = np.array([1, 2, 3, 4, 5, 6])
   reshaped_array = original_array.reshape((2, 3))  # Reshape to 2x3 array
   ```

These are just some basic operations, and NumPy offers a wide range of functions and methods for more advanced manipulations of arrays. Understanding these basics is crucial for working with data in various scientific and data science applications.

In NumPy, the term "dimensions" refers to the size or extent of each axis in an array. Arrays can be one-dimensional, two-dimensional, or multi-dimensional, and understanding the dimensions of an array is essential for indexing, slicing, and performing various operations.

### 1. **One-Dimensional Arrays:**
   - A one-dimensional array is essentially a list of elements.
   - Accessing elements involves specifying a single index.

   ```python
   import numpy as np

   arr_1d = np.array([1, 2, 3, 4, 5])
   print(arr_1d[2])  # Accessing the third element
   ```

### 2. **Two-Dimensional Arrays:**
   - Two-dimensional arrays are like tables with rows and columns.
   - Accessing elements requires specifying row and column indices.

   ```python
   arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
   print(arr_2d[1, 2])  # Accessing the element in the second row, third column
   ```

### 3. **Multi-Dimensional Arrays:**
   - Arrays with more than two dimensions are considered multi-dimensional.
   - Accessing elements involves specifying indices along each dimension.

   ```python
   arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
   print(arr_3d[1, 0, 1])  # Accessing the element in the second "layer," first row, second column
   ```

### 4. **Shape of an Array:**
   - The shape of an array is a tuple indicating the size along each dimension.
   - The `shape` attribute provides information about the array's dimensions.

   ```python
   print(arr_1d.shape)  # Output: (5,)
   print(arr_2d.shape)  # Output: (3, 3)
   print(arr_3d.shape)  # Output: (2, 2, 2)
   ```

### 5. **Reshaping Arrays:**
   - You can change the shape of an array using the `reshape` method.
   - The reshaped array should have the same number of elements as the original.

   ```python
   reshaped_arr = arr_1d.reshape((5, 1))  # Reshape to a column vector
   ```

### 6. **Adding Dimensions:**
   - You can add dimensions to an existing array using `np.newaxis` or `np.expand_dims`.

   ```python
   new_dim_arr = arr_1d[:, np.newaxis]  # Adding a new axis to create a column vector
   ```

### 7. **Array Transposition:**
   - Transposing an array swaps its dimensions.
   - For a 2D array, this means switching rows and columns.

   ```python
   transposed_arr_2d = arr_2d.T
   ```

Understanding and managing dimensions in NumPy arrays is crucial when performing operations, reshaping data, and interfacing with other libraries and tools in the data science ecosystem. It's important to be aware of the shape and size of your arrays to ensure compatibility and correctness in various mathematical and machine learning operations.