Create NumPy Arrays with Random Numbers
- rand(): the function is used to generate a random value between 0 and 1
- randn(): the function is used to generate a random value close to zero. This may return positive or negative numbers.
- ranf(): the function for doing random sampling in numpy. It returns an array of specified shape and fills it with random floats in the half open interval [0.0, 1.0)
- randint(): the function is used to generate a random number between a given range

rand()

In [1]:
import numpy as np

var = np.random.rand(4) # 1d
print(var)

[0.78988634 0.33693868 0.69205141 0.91564497]


In [2]:
var1 = np.random.rand(2,5) #2d
print(var1)

[[0.13189061 0.16815887 0.68674355 0.26373685 0.59704822]
 [0.16145801 0.21867471 0.75853545 0.65259813 0.64645129]]


randn()

In [3]:
var2 = np.random.randn(5)
print(var2)

[-0.44226636 -0.13217602  0.32224313  1.34360819 -0.25263663]


ranf()

In [4]:
var3 = np.random.ranf(4)
print(var3)

[0.65258909 0.63665681 0.34114466 0.36474276]


randint()

In [6]:
var4 = np.random.randint(5,20,5) # min,max, total_values
print(var4)

[15 19 10 14 10]
